### ISSUE TITLE
Snap before Stop

### ISSUE THREAD

**Issue by AlmondFace** [guidobouman/jquery-panelsnap#68]
Hi, thanks for this amazing plugin, i was trying a few others but this works perfectly on my iOS devices which is what i was looking for.

Is there a way to allow the panels to snap before the scroll has finished? This is seen a lot on iOS newsstand apps, where navigating vertically to the next panel snaps into place before the scroll action has completely finished.

Any help here would be amazing, thanks

**Comment by Dheirya** [comment]
It's been about 7 years since this thread got commented on and I'm not sure if anyone is still working on this repository, but...

I'm trying to make a tiktok-style website and I need the scroll to snap before the user stops scrolling, because I want to make the scrolling feel "natural" and I want it to feel like Tiktok. 

I think that in some situations, ScrollJacking is ok and I would like to see this feature added if anyone is still working.
