### ISSUE TITLE
Doesn't work for sections with height "200vh"

### ISSUE THREAD

**Issue by robpoole** [guidobouman/jquery-panelsnap#77]
When setting up a site with sections that are 2x the viewport height the plugin doesn't work. When scrolling to the first section the plugin kicks in and scrolls all the way to the bottom on the page.

**Comment by guidobouman** [comment]
What if you use a pixel height value?

And do you have a live testing url?

**Comment by gvdm** [comment]
I have a similar issue, with uneven sized sections (minimum size is equal to scrolling container) when scrolling down the plugin will scroll to the last section. This seems to happen whenever any section is larger than the scrolling container. Ideally, the plugin would hold off snapping till the end of the section has been scrolled to. Furthermore, to aid identification of the bug, the plugin will keep snapping to the last section even if one is to try scrolling back up through sections. Please see http://jsfiddle.net/pspp9veg/1/ for an example, the first snap is fine, thereafter problematic. Have a go.

**Comment by ynaveed** [comment]
I have sorted down the problem to the function scrollStop. The childNumber exceeds the value of panelCount and therefore it scrolls to the bottom of the page. As stated above, this happens when the panels are short in height and of variable sizes. For me this particularly happens at around 700px height.  I'll update when I have a solution

**Comment by ynaveed** [comment]
It's dirty solution, but I made to work. Instead of using the scroll offsets to judge which panel should it snap to, I used the given function getPanelsInView to get the panels. As their can be at max 2 panels in view (in my case at least), I keep a direction variable (up/down) and pass one of the panels for snapping.

**Comment by guidobouman** [comment]
That's actually quite smart @ynaveed! I'll take a look at it this this weekend.

**Comment by gvdm** [comment]
Would this also be related to the display breaking in a similar fashion when some sections are "display:none;"? Hopefully this fixes that too.

**Comment by gvdm** [comment]
@guidobouman any chance of this getting into trunk?

**Comment by theones** [comment]
@ynaveed ynaveed can you send some code of that ?

**Comment by ynaveed** [comment]
https://github.com/ynaveed/jquery-panelsnap/tree/quickFix

**Comment by guidobouman** [comment]
You seem to have forgotten to push your changes to that branch.

**Comment by ynaveed** [comment]
Oh yes, sorry for that. Please check now.

Regards,
Yasir
