### ISSUE TITLE
Unwanted delay in all browsers except Chrome

### ISSUE THREAD

**Issue by ThomasPe** [guidobouman/jquery-panelsnap#83]
There's an unwanted delay IE, Firefox and I think also in Safari even though the delay parameter is set to 0. This delay is caused by  the setTimeout in line 628.I tried setting the offset to 0 and the setTimeout to 10 so it's barely noticable anymore, but then the scrolling is quite buggy. Chrome is the only browser that seems to work as inteded.

**Comment by guidobouman** [comment]
That delay is present because you want to detect when the user is done scrolling. If you lower the delay amount too much it'll make the scrolling buggy as you noticed. That's because there's kinetic scrolling in a lot of browsers which breaks if you lower the timeout below the current 50 milliseconds.

This is known behaviour. And unfortunately, will not change. Not until we have a better mechanism of detecting when a user stops scrolling.
